version: "3"
services:
  db:
    image: "postgres:14"
    container_name: te-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "db_data:/var/lib/postgresql/data"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: te-backend
    environment:
      - DJANGO_DB_TYPE=postgres
      - DJANGO_DEBUG
      - DJANGO_ALLOWED_HOSTS
      - NGINX_DOMAIN_NAME
    volumes:
      - "./logs/backend:/var/www/backend/logs"
      - "backend_media:/var/www/backend/media"
      - "backend_static:/var/www/backend/static"
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    image: "nginx:1.23"
    container_name: te-nginx
    environment:
      - NGINX_DOMAIN_NAME
    volumes:
      - "./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro"
      - "./logs/nginx:/var/log/nginx"
      - "backend_media:/var/www/backend/media:ro"
      - "backend_static:/var/www/backend/static:ro"
    ports:
      - "${NGINX_HTTP_PORT}:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
  backend_media:
  backend_static:
