# Generated by Django 4.1.1 on 2022-10-17 13:45

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата измерения')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='product name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='product name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='product name')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='icon')),
                ('is_green', models.BooleanField(verbose_name='is green')),
                ('type', models.CharField(choices=[('food', 'Food'), ('drink', 'Drink')], max_length=8, verbose_name='product type')),
                ('hint', models.CharField(max_length=255, verbose_name='hint')),
                ('hint_en', models.CharField(max_length=255, null=True, verbose_name='hint')),
                ('hint_ru', models.CharField(max_length=255, null=True, verbose_name='hint')),
                ('default_portion_size', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='default user portion size')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
