# Generated by Django 4.1.1 on 2022-10-17 20:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_alter_product_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата измерения')),
                ('default_portion_size_override', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='default user portion size')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='products.product', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user product info',
                'verbose_name_plural': 'user product info',
            },
        ),
        migrations.AddConstraint(
            model_name='userproductinfo',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='unique_product_user'),
        ),
    ]
