# Generated by Django 4.1.1 on 2022-10-18 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_userproductinfo_userproductinfo_unique_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductinfo',
            name='default_portion_size_override',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='default user portion size'),
        ),
    ]
