# Generated by Django 4.1.1 on 2022-10-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_userproductinfo_default_portion_size_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hint',
            field=models.CharField(blank=True, max_length=255, verbose_name='hint'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hint_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='hint'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hint_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='hint'),
        ),
    ]
