# Generated by Django 4.1.1 on 2022-11-22 13:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_alter_product_hint_alter_product_hint_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ghg',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='greenhouse gas amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='land',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='land area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='water',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='water volume'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='userproductinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='userproductinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.CreateModel(
            name='UserProductConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('portion_size', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='portion size')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'product consumption',
                'verbose_name_plural': 'product consumption',
            },
        ),
    ]
