# Generated by Django 4.1.1 on 2022-11-22 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_ghg_product_land_product_water_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductconsumption',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date'),
        ),
    ]
